### ISSUE TITLE
TicketCreate视图没有将提交的表单写入数据库？

### ISSUE THREAD

**Issue by GSshu** [jimmy201602/workflowdemo#10]
我在复现这个demo，提交创建的表单是没有写入数据库里面吗？我创建的还是原来的数据库导入的，请问如果想要实现创建的请假申请导入数据库里面，还需要怎么修改？是我的参数没有设置好吗？从数据库删除到前端是可以显示的。

**Comment by blackholll** [comment]
workflowdemo的前端请求workflowdemo后端， 然后workflowdemo后端调用loonflow的api。

**Comment by jimmy201602** [comment]
欢迎pr
