### ISSUE TITLE
如果只是单纯调用接口数据，workflow的views函数应当如何修改？

### ISSUE THREAD

**Issue by GSshu** [jimmy201602/workflowdemo#11]
您好，我现在要将您的网页视图 替换成微信小程序的前端展示，但是views里面的函数是用的网页模板，请问如果要将后端的函数修改为只获取数据，这个可行吗？我需要返回工作流引擎的数据，并不需要这些TemplateView的网页。

**Comment by blackholll** [comment]
两种选择：
1.自己写个后端，这个后端处理登录(小程序的登录)。然后这个后端直接调用loonflow的接口完成工单相关逻辑
2.参考下https://github.com/youshutong2080/shutongFlow  这个是前后端分离的demo。 你可以只用他的后端部分。 不过你还是需要自己处理小程序的登录问题

**Comment by GSshu** [comment]
小程序的登录已经实现，shutongflow的vue部分比较麻烦，我没搞明白，您的意思是我如果绕过登录部分，shutong的后端接口我能够进行调用吗？

**Comment by blackholll** [comment]
那你就选在方案1吧。  你都实现登录部分了, 再写个签名如认证逻辑 来直接调用https://github.com/blackholll/loonflow 的接口就可以了。 签名方法 https://github.com/blackholll/loonflow/blob/master/docs/apis/index.md
