### ISSUE TITLE
页面展示列表最多是10个，并且只有一页，和数据库记录个数不相符，该如何修改？

### ISSUE THREAD

**Issue by GSshu** [jimmy201602/workflowdemo#13]
进行工单查询的时候发现所有、未处理页面展示都是最多有十个，页面的显示next和previous都不能点，只有一页展示，这个是哪里的参数没有设置好吗？
还有一个问题是数据库里面的数据有很多条，通过/api/v1.0/tickets能够查询到相应的数据，我想要查询workflow_id =1的时候把参数传进 def get_ticket_list(cls, sn='', title='', username='', create_start='', create_end='', workflow_ids='', state_ids='', ticket_ids= '', category='', reverse=1, per_page=10, page=1, app_name='', is_end='', is_rejected=''): 返回的还是所有的数据，这个是不能传进去吗？

**Comment by blackholll** [comment]
1.应该是前端分页这块没处理好吧  @jimmy201602 
2.不支持workflow_id参数， 是workflow_ids参数， 字符串类型，多个id用逗号隔开，比如需要查询workflow_id为1和2的那么workflow_ids传"1,2" .如果只是1那么workflow_ids传"1"

**Comment by jimmy201602** [comment]
欢迎pr
