### ISSUE TITLE
你好，在发起页面填写的值是有效的，但在下一个审批中填写的值都报错

### ISSUE THREAD

**Issue by 1398994041** [jimmy201602/workflowdemo#14]
你好，在发起页面填写的值是有效的，但在下一个审批中填写的值都报
![微信图片_20190719110059](https://user-images.githubusercontent.com/10649004/61506486-d8825a00-aa14-11e9-94d1-e99197f1096b.jpg)
错

**Comment by GSshu** [comment]
请问这样的情况要如何处理比较合适呢？

**Comment by blackholll** [comment]
应该是处理工单的页面 点击操作按钮后并没有将需要填写的字段的值在 调用loonflow接口时传过来， loonflow报错的。
检查下是否是最新代码。记得之前有人提过pr修复 处理工单页面对必填和可选字段的处理

**Comment by jimmy201602** [comment]
Any pr will be appreciated.
