### ISSUE TITLE
当工作流状态分配方式为主动接单并且参与人为多人时，无法接单

### ISSUE THREAD

**Issue by xllc** [jimmy201602/workflowdemo#18]
![WechatIMG885](https://user-images.githubusercontent.com/25189872/69741812-a927ea80-1176-11ea-80c9-b3c25be4dc0a.jpeg)
直接用docker上的镜像跑的。默认的VPN权限申请流程到第三步也是这样。

**Comment by jimmy201602** [comment]
demo需要按需二次开发
