### ISSUE TITLE
請問workflowdemo在本地怎麼配置成功，點擊‘我所創建的’，返回‘string indices must be integers’錯誤？急求！

### ISSUE THREAD

**Issue by JochimLiu** [jimmy201602/workflowdemo#5]

**Comment by JochimLiu** [comment]
{"code": -1, "msg": "权限校验失败：未提供appname(调用loonflow接口需要鉴权，请根据文档中\"调用授权\"部分说明来调用", "data": []}

**Comment by blackholll** [comment]
workflowdemo的前端调用的是workflowdemo的后端，然后workflowdemo后端调用loonflow:https://github.com/blackholll/loonflow.

**Comment by JochimLiu** [comment]
假設workflowdemo的ip是127.0.0.1:8001，loonflow的後端ip是127.0.0.1:8888，我（admin）在loonflow admin後台的apptoken中配置ops的app和令牌，這兩個在workflowdemo的setting.py裡設好方便後端程序調用。這一些搞好後，在瀏覽器上打開127.0.0.1:8888/api/v0.1/workflows,出現上面的錯誤提示。我哪裡除了問題？

**Comment by blackholll** [comment]
在浏览器直接请求127.0.0.1:8888/api/v0.1/workflows 是直接请求的loonflow(没带任何header 签名信息)。  loonflow这个文件里面有个校验或获取header中的信息来做校验:https://github.com/blackholll/loonflow/blob/master/service/permission/api_permission.py  所以会报错。  workflowdemo的逻辑是workflowdemo的前端调用workflowdemo后端，然后后端会根据settings里面的token信息生成签名然后再调用loonflow的后端

**Comment by JochimLiu** [comment]
沒弄的太明白，，，我遇到的問題是這樣子，workflowdemo後端是通過在https://github.com/jimmy201602/workflowdemo/blob/master/workflow/apirequest.py中的第32行代碼進行data獲取的吧，其中我的headers:{'signature': '78095a1bf6e7800e763e9f143270f434', 'timestamp': '1551265870', 'app_name': 'ops'},parameters{'username': 'admin', 'per_page': 20, 'name': ''},r的返回結果是http411,workflowdemo前端的index上新建工單字段下一片空白。怎麼解決？謝謝告知！

**Comment by blackholll** [comment]
加qq群说吧 :   558788490

**Comment by JochimLiu** [comment]
r = getattr(requests, method)('{0}{1}'.format(self.workflowbackendurl,url), headers=headers, params=parameters,timeout=timeout,data=json.dumps(data));
這段代碼當method=get時返回http411的錯誤，post則是http403access denied，辦公室用不了qq，先在這發了。

**Comment by JochimLiu** [comment]
http411時的錯誤txt：
While trying to process the request:
<PRE>
GET /api/v1.0/workflows?username=admin&amp;per_page=20&amp;name= HTTP/1.1
Host: 127.0.0.1:8899
User-Agent: python-requests/2.19.1
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
signature: 679e85bfd7909b1dd747ae1f02c749fa
timestamp: 1551406743
appname: ops
Content-Length: 2
Proxy-Authorization: Basic Rjc2ODczNTQ6TTRXNWt3aHI=

</PRE>
<P>
The following error was encountered:
<UL>
<LI>
<STRONG>
Invalid Request
</STRONG>
</UL>

<P>
Some aspect of the HTTP Request is invalid.  Possible problems:
<UL>
<LI>Missing or unknown request method
<LI>Missing URL
<LI>Missing HTTP Identifier (HTTP/1.0)
<LI>Request is too large
<LI>Content-Length missing for POST or PUT requests
<LI>Illegal character in hostname; underscores are not allowed
</UL>

**Comment by jimmy201602** [comment]
请检查后端日志,lonnflow问题请去lonnflow提issue
