### ISSUE TITLE
Docker异常

### ISSUE THREAD

**Issue by yslhzj** [jimmy201602/workflowdemo#6]
你好,问题如下:
![qq 20190303142807](https://user-images.githubusercontent.com/29890756/53691825-abfcd700-3dc0-11e9-93d9-c364b02a069e.jpg)
镜像已从git上下载下来了,如上图所示.但在运行出现上述问题.(docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:293: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown.)

[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

**Comment by blackholll** [comment]
试试这个 https://www.jianshu.com/p/8fbd83627c99
