### ISSUE TITLE
这里应该改为in数组，而不是等号比较

### ISSUE THREAD

**Issue by JakLiao** [jimmy201602/workflowdemo#7]
https://github.com/jimmy201602/workflowdemo/blob/cc69ef73447ac8c2f1a22eae4e00f26e956f8c30/workflow/views.py#L179

elif field['field_type_id'] in [FIELD_TYPE_CHECKBOX, FIELD_TYPE_MULTI_SELECT]:

**Comment by jimmy201602** [comment]
fixed
